spring:
  config:
    activate:
      on-profile: prod

  datasource:
    major:
      driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://velysound.synology.me:5432/jindamhair
      username: jindamhair
      password: jindamhair1!
      min-idle: 5
      max-pool-size: 30
      max-lifetime: 1800000
      auto-commit: true

springdoc:
  swagger-ui:
    enabled: true # 운영 UI 비활성(원하면 true)
  api-docs:
    enabled: true # 스펙 엔드포인트도 기본 비활성

management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8081 # 운영 모니터링 포트 분리하고 싶을 때 (원치 않으면 제거)

server:
  port: 8080
  # servlet:
  #   context-path: /api

Globals:
  # osType: mac
  # osType: window
  osType: linux
  
  # Log settings
  log:
    filename: application
    error-filename: ${log.filename}_err
  
  # Path settings
  path:
    mac:
      root: /Users/bbamkeylee/dev
      log: ${Globals.path.mac.root}/logs
      upload: ${Globals.path.mac.root}/upload
    window:
      root: C:\\Users\\beomg\\dev
      log: ${Globals.path.window.root}\\logs
      upload: ${Globals.path.window.root}\\upload
    linux:
      root: /jindamhair/tomcat
      log: ${Globals.path.linux.root}\\logs
      upload: ${Globals.path.linux.root}\\upload
    upload: ${Globals.path.${Globals.osType}.upload}
    log: ${Globals.path.${Globals.osType}.log}