spring:
  config:
    activate:
      on-profile: local

  datasource:
    major:
      driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://velysound.synology.me:5432/jindamhair
      username: jindamhair
      password: jindamhair1!
      min-idle: 2
      max-pool-size: 10
      max-lifetime: 1800000
      auto-commit: true

  # 개발 편의
  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

Globals:
  # osType: mac
  osType: window
  # osType: linux
  
  # Log settings
  log:
    filename: application
    error-filename: ${log.filename}_err
  
  # Path settings
  path:
    mac:
      root: /Users/bbamkeylee/dev
      log: ${Globals.path.mac.root}/logs/jindamhair-backend
      upload: ${Globals.path.mac.root}/upload/jindamhair-backend
    window:
      root: C:\dev\logs
      log: ${Globals.path.window.root}\\logs\\jindamhair-backend
      upload: ${Globals.path.window.root}\\upload\\jindamhair-backend
    linux:
      root: /jindamhair/tomcat
      log: ${Globals.path.linux.root}/logs/jindamhair-backend
      upload: ${Globals.path.linux.root}/upload/jindamhair-backend
    upload: ${Globals.path.${Globals.osType}.upload}
    log: ${Globals.path.${Globals.osType}.log}